/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MassCreatePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// modal/CreationModal.ts
var import_obsidian2 = require("obsidian");

// processing/NewNotes.ts
var import_obsidian = require("obsidian");
var NewNotes = class {
  async createBulkNotes(note, path, app, contentPath) {
    const normalizedPath = (0, import_obsidian.normalizePath)(path);
    const folder = app.vault.getAbstractFileByPath(normalizedPath);
    if (!folder) {
      app.vault.createFolder(normalizedPath);
    }
    if (contentPath == "") {
      app.vault.create(path + "/" + note + ".md", "");
    } else {
      const normalizedPath2 = (0, import_obsidian.normalizePath)(contentPath);
      const templateFile = app.vault.getAbstractFileByPath(normalizedPath2);
      if (templateFile && templateFile instanceof import_obsidian.TFile) {
        const content = await app.vault.read(templateFile);
        app.vault.create(path + "/" + note + ".md", content);
      }
    }
  }
};

// modal/CreationModal.ts
var CreationModal = class extends import_obsidian2.Modal {
  constructor(app, path) {
    super(app);
    this.isFolderCreating = false;
    this.path = path;
    this.templatePath = "";
  }
  onOpen() {
    this.display();
  }
  onClose() {
    let { contentEl } = this;
    contentEl.empty();
  }
  display() {
    let { contentEl } = this;
    this.contentEl.empty();
    this.add_create_title(contentEl);
    this.add_create_folder(contentEl);
    this.add_add_note_names(contentEl);
    this.add_use_template(contentEl);
    if (this.usingTemplate) {
      this.add_template_path(contentEl);
    }
    this.add_create_button(contentEl);
  }
  add_create_title(contentEl) {
    contentEl.createEl("h1", { text: "Mass create notes" });
  }
  add_create_folder(contentEl) {
    new import_obsidian2.Setting(contentEl).addText(
      (text) => text.setValue(this.folderName).setPlaceholder("Folder name").setDisabled(!this.isFolderCreating).onChange((folderName) => {
        this.folderName = folderName;
      })
    ).addToggle((toggle) => {
      toggle.setValue(this.isFolderCreating).onChange((isFolderCreating) => {
        this.isFolderCreating = isFolderCreating;
        this.folderName = "";
        this.display();
      });
    }).setName("Create folder").setDesc("Creates optional folder for files.");
  }
  add_add_note_names(contentEl) {
    new import_obsidian2.Setting(contentEl).addTextArea((text) => {
      const t = text.setValue(this.textAreaNames).setPlaceholder("Note names").onChange((value) => {
        this.textAreaNames = value;
      });
      t.inputEl.setAttr("rows", 13);
      t.inputEl.setAttr("cols", 65);
    }).setName("Note names").setDesc("List each note on its own line.");
  }
  add_use_template(contentEl) {
    new import_obsidian2.Setting(contentEl).setName("Use template?").addToggle((cb) => {
      cb.setValue(this.usingTemplate).onChange((usingTemplate) => {
        this.usingTemplate = usingTemplate;
        this.display();
        this.templatePath = "";
      });
    });
  }
  add_template_path(contentEl) {
    new import_obsidian2.Setting(contentEl).setName("Template path:").setDesc("Path from template folder.").addText((text) => {
      text.setPlaceholder("Path/Note.md").onChange((templatePath) => {
        this.templatePath = templatePath;
      }).setValue(this.templatePath);
    });
  }
  add_create_button(contentEl) {
    new import_obsidian2.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Create").setCta().onClick(() => {
        this.close();
        this.display_names();
        const notesList = this.textAreaNames.split("\n");
        for (let i = 0; i < notesList.length; i++) {
          if (this.usingTemplate) {
            if (this.isFolderCreating) {
              new NewNotes().createBulkNotes(
                notesList[i],
                this.path + "/" + this.folderName,
                this.app,
                this.templatePath
              );
            } else {
              new NewNotes().createBulkNotes(
                notesList[i],
                this.path,
                this.app,
                this.templatePath
              );
            }
          } else {
            if (this.isFolderCreating) {
              new NewNotes().createBulkNotes(
                notesList[i],
                this.path + "/" + this.folderName,
                this.app,
                ""
              );
            } else {
              new NewNotes().createBulkNotes(
                notesList[i],
                this.path,
                this.app,
                ""
              );
            }
          }
        }
      });
    });
  }
  display_names() {
    const annNames = this.textAreaNames.split("\n");
    let output = "";
    for (let i = 0; i < 5 && i < annNames.length; i++) {
      output += annNames[i] + "\n";
    }
    if (annNames.length > 5) {
      output += "and " + (annNames.length - 5) + " more have been created.";
    } else {
      output += "notes have been created.";
    }
    new import_obsidian2.Notice(output);
  }
};

// processing/Detector.ts
var import_obsidian3 = require("obsidian");
var Detector = class {
  getActiveFolder(app) {
    var _a;
    const activeFile = app.workspace.getActiveFile();
    if (activeFile && activeFile instanceof import_obsidian3.TFile) {
      return ((_a = activeFile.parent) == null ? void 0 : _a.path) || "";
    }
    return "";
  }
};

// main.ts
var MassCreatePlugin = class extends import_obsidian4.Plugin {
  async onload() {
    this.addCommand({
      id: "display-creation-modal",
      name: "Note creator",
      callback: () => {
        new CreationModal(this.app, new Detector().getActiveFolder(this.app)).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, folder) => {
        if (folder && folder instanceof import_obsidian4.TFolder) {
          menu.addItem((item) => {
            item.setTitle("Mass create notes").setIcon("plus").onClick(async () => {
              this.folderPath = folder.path;
              new CreationModal(
                this.app,
                this.folderPath
              ).open();
            });
          });
        }
      })
    );
  }
  onunload() {
  }
};


/* nosourcemap */